kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: crossplane
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30183
    hostPort: 30183
    listenAddress: "127.0.0.1"
    protocol: TCP
